function plot_profile(base, alphas, innerCones, outerCones, v_prof)
    
    subplot(2,1,1);
        plot_track(innerCones,outerCones);
        hold on;
        plot_base(base);
        print_markers(base, alphas);
        pts = get_points(base, alphas);
        colors = generateHeatmapColors(v_prof);
        for I = 1:length(v_prof)-1
            plot(pts(I:I+1, 1), pts(I:I+1, 2), 'x-', 'Color', colors(I, :), 'MarkerSize', 8, 'LineWidth', 1.5);
        end
    subplot(2,1,2);
    plot(1:length(v_prof), v_prof, "Color","green", "Marker","o");
end

function colorArray = generateHeatmapColors(velocities)
    % Generate a heatmap color array based on a list of velocities
    % Inputs:
    %   velocities - a vector of velocities
    % Outputs:
    %   colorArray - an Nx3 array of RGB colors

    % Normalize velocities to range [0, 1]
    minVel = min(velocities);
    maxVel = max(velocities);
    normalizedVelocities = (velocities - minVel) / (maxVel - minVel);

    % Use a colormap (e.g., jet) to map normalized velocities to colors
    colormapName = jet(256); % 256-color jet colormap
    colorIndices = round(normalizedVelocities * 255) + 1; % Map to colormap index
    colorArray = colormapName(colorIndices, :); % Get RGB colors
end
%This function was generated by ChatGPT 4.o at 12.12.2024